11/08/2025-23:56:48 CRM is alive - GraphQL endpoint error: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /graphql/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a3d6fe1b710>: Failed to establish a new connection: [Errno 111] Connection refused'))
